{{- if .Values.mongo.enabled}}
{{- $context := merge (dict "key" "mongo") $ }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "planufacture.fullname" $context }}
  labels:
    {{- include "planufacture.labels" $context | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  {{- if .Values.mongo.password }}
  mongo-root-password: {{ .Values.mongo.password | b64enc | quote }}
  {{- else }}
  mongo-root-password: {{ randAlphaNum 15 | b64enc | quote }}
  {{- end }}
{{- end }}
