{{- range $key, $val := .Values.microServices }}
{{- $context := merge (dict "key" ($key | kebabcase)) $ }}
{{- if .mongo }}
{{- if not (lookup "v1" "Secret" $.Release.Namespace (include "planufacture.fullname" $context)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "planufacture.fullname" $context }}
  labels:
    {{- include "planufacture.labels" $context | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
stringData:
  {{- $password := .mongo.password | default (randAlphaNum 20) }}
  mongo-uri: "mongodb://{{ $context.key }}:{{ $password }}@mongo:27017/{{ .mongo.db }}?authSource=admin"
  mongo-password: {{ $password }}
{{- end -}}
{{- end }}
---
{{ end }}
