---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "planufacture.fullname" $ }}-solver
  labels:
    {{- include "planufacture.labels" . | nindent 4 }}
data:
  clientId: {{ required "A valid .Values.solver.clientId is required" .Values.solver.clientId | b64enc | quote }}
  clientSecret: {{ required "A valid .Values.solver.clientSecret is required" .Values.solver.clientSecret | b64enc | quote }}

