---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "planufacture.fullname" $ }}-configuration
  labels:
    {{- include "planufacture.labels" . | nindent 4 }}
stringData:
  application.yaml: {{ required "A valid .Values.configuration" .Values.configuration | b64enc | quote }}

