{{- if .Values.axonserver.enabled}}
{{- $context := merge (dict "key" "axonserver-license") $ }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "planufacture.fullname" $context }}
  labels:
    {{- include "planufacture.labels" $context | nindent 4 }}
data:
  axoniq.license: ""
{{- end }}
